spring.application.name=samplePJ-TODO
spring.thymeleaf.mode=HTML

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datasource.username=${DB_USER:todo_app_user}
spring.datasource.password=${DB_PASSWORD}

logging.level.sample.*=DEBUG

mybatis.type-aliases-package=sample.common.dao.entity
mybatis.mapper-locations=classpath:sample/common/dao/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

server.servlet.session.timeout=1d