spring.application.name=samplePJ-TODO
spring.thymeleaf.mode=HTML

password.hash.code=SHA-256

spring.datesource.driver-class-name=org.postgresql.Driver
spring.datesource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datesource.username=postgres
spring.datesouce.password=root

logging.level.sample.*=DEBUG

mybatis.type-aliases-package=sample.common.dao.entity
mybatis.mapper-locations=classpath:sample/common/dao/mapper/*.xml

server.servlet.session.timeout=1d