spring.application.name=samplePJ-TODO
spring.thymeleaf.mode=HTML

password.hash.code=SHA-256

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datasource.username=postgres
spring.datasource.password=yukao0719

logging.level.sample.*=DEBUG

mybatis.type-aliases-package=sample.common.dao.entity
mybatis.mapper-locations=classpath:sample/common/dao/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

server.servlet.session.timeout=1d